project_id = "gcqfqzhgludrzkfajljp"

[functions.sync-store]
verify_jwt = false

[functions.chat-with-tessa]
verify_jwt = false

[functions.chat-with-tessa-secure]
verify_jwt = false

[functions.system-status]
verify_jwt = false
